services:
  # 
  # This isn't required since we're using postgres-meta as a JS lib.
  #
  # meta:
  #   image: supabase/postgres-meta
  #   ports:
  #     - 8080:8080
  #   volumes:
  #   - .:/docker-entrypoint-initdb.d
  #   environment: 
  #     PG_META_PORT: 8080
  #     PG_META_DB_HOST: "db"
  #     PG_META_DB_NAME: "postgres"
  #     PG_META_DB_USER: "postgres"
  #     PG_META_DB_PORT: 5432
  #     PG_META_DB_PASSWORD: "postgres"
  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
    - ./db:/docker-entrypoint-initdb.d
    environment: 
      POSTGRES_PASSWORD: postgres
